config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  get 'users/sign_out', to: 'devise/sessions#destroy'
  root 'homes#index'
  get '/homes/introduction', to: 'homes#introduction'

  resources :buildings
end

app/views/shared/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-wrapper">   
  <footer class="fixed-bottom">  
    <div class="container">
      <span class="copyright">
        &copy; Copyright <a href="/" target="_blank">Fire Fighting Equipment</a> All Rights Reserved.
      </span>
    </div>
  <footer>
</div>

app/views/shared/_header.html.erb
<header class="sticky-top">
  <div class="header">
    <nav class="navbar navbar-default navbar-expand-md navbar-light py-0 color__navi">
      <%= link_to image_tag("logo2.png"), root_path, class: 'logo', 'data-turbolinks': :false %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false">
        <span class="navbar-toggler-icon"></span>
        <span class="toggler__txt"></span>
      </button>
      <div class="navbar-collapse collapse flex-column align-items-end pb-3 pb-md-0" id="navbarContent">
        <ul class="nav__main navbar-nav order-md-2 mt-3">
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "Edit user",  edit_user_registration_path, class: "nav-link px-4" %></li>
            <li class="nav-item"><%= link_to "Log out", destroy_user_session_path, data: { confirm: "ログアウトしますか？" }, class: "nav-link px-4"%></li>
          <% else%>
            <li class="nav-item"><%= link_to "新規登録", new_user_registration_path, class: "nav-link px-4" %></li>
            <li class="nav-item"><%= link_to "Log in", new_user_session_path, class: "nav-link px-4" %></li>
            <li class="nav-item"><%= link_to "Guest", users_guest_sign_in_path, method: :post, class: " nav-link px-4"%></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
  <div class="header-nav">
    <div class="container">
      <div class="row header-nav-box" data-turbolinks="false">
        <% if user_signed_in? %>
          <%= link_to "Home", root_path, class: "col-xs-4 col-sm-4 header-nav-btn" %>
          <%= link_to "Building", new_building_path, class: "col-xs-4 col-sm-4 header-nav-btn" %>
          <%= link_to "Search", buildings_path, class: "col-xs-4 col-sm-4 header-nav-btn" %>
        <% else %>  
          <%= link_to "Home", root_path, class: "col-xs-4 col-sm-4 header-nav-btn" %>
          <%= link_to "About", root_path( anchor: "about" ), class: "col-xs-4 col-sm-4 header-nav-btn" %>
          <%= link_to "Introduction", homes_introduction_path, class: "col-xs-4 col-sm-4 header-nav-btn" %>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/shared/_mainVisual.html.erb
<div id="carousel-1" class="carousel slide carousel-fade" data-ride="carousel" data-interval="4000">
  <ol class="carousel-indicators">
    <li data-target="#carousel-1" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-1" data-slide-to="1"></li>
    <li data-target="#carousel-1" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block img-fluid-1" src="/assets/syoubousya2.jpeg" alt="First slide">
      <div class="carousel-caption d-none d-sm-block">
        <h2>Fire Fighting Equipment</h2>
        <p>samplesamplesamplesamplesample</p>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block img-fluid-2" src="/assets/syoubousya3.jpeg" alt="Second slide">
      <div class="carousel-caption d-none d-sm-block">
        <h2>Fire Fighting Equipment</h2>
        <p>samplesamplesamplesamplesample</p>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block img-fluid-3" src="/assets/syoubousya4.jpeg" alt="Third slide">
      <div class="carousel-caption d-none d-sm-block">
        <h2>Fire Fighting Equipment</h2>
        <p>samplesamplesamplesamplesample</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-1" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_section.html.erb
<div id="about" class="section about">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-lg-12">
        <div class="col-xs-6 col-sm-12">
          <%# <img src="assets/syoubousya1.png" alt="" class="img-responsive" style="width:100%;"/> %>
        </div>
        <div class="col-xs-6 col-sm-12">
          <h4>About</h4>
          <p>webアプリケーションの概要を説明します。</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <div class="card-link">
        <%= link_to homes_introduction_path, 'data-turbolinks': :false do %>
          <div class="card-group top-card scroll-reveal">
            <div class="card h-100">
              <img src="assets/automatic_fire_alarm_equipment.png" alt="" class="img-responsive w-100">
              <div class="card-body">
                <h4>Introduction</h4>
                <p class="card-text">一般的によく使われている各消防用設備について説明します。</p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="card-link">
        <%= link_to new_building_path, 'data-turbolinks': :false do %>
          <div class="card-group top-card scroll-reveal">
            <div class="card h-100">
              <img src="assets/building.png" alt="" class="img-responsive w-100">
              <div class="card-body">
                <h4>Building</h4>
                <p class="card-text">名称や住所などの建物情報を登録することができます。</p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="card-link">
        <%= link_to buildings_path, 'data-turbolinks': :false do%>
          <div class="card-group top-card scroll-reveal">
            <div class="card h-100">
              <img src="assets/syoukaki.png" alt="" class="img-responsive w-100">
              <div class="card-body">
                <h4>Search</h4>
                <p class="card-text">登録された建物情報から、必要な消防用設備を知ることができます。</p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>