config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  get 'users/sign_out', to: 'devise/sessions#destroy'
  root 'homes#index'
  get '/homes/introduction', to: 'homes#introduction'

  resources :buildings
end

app/models/building.rb
class Building < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :entirety_usege_id, presence: { message: "を選択してください" }
  validates :building_type_id, presence: true

  belongs_to :user
  belongs_to :entirety_usege, optional: :true
  belongs_to :building_type
  belongs_to :fire_use
  has_many :information_by_floors, dependent: :destroy
  accepts_nested_attributes_for :information_by_floors, allow_destroy: true
end

app/models/building_type.rb
class BuildingType < ApplicationRecord
  has_many :buildings
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_up_building, only: [:show, :edit, :update, :destroy]
  before_action :set_up_form, only: [:new, :create, :edit, :update]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # 一覧画面に対するアクション
  def index
    @buildings = Building.where(user_id: current_user.id).order(:id).paginate(page: params[:page], per_page: 4)
  end

  # 新規作成画面に対するアクション
  def new
    @building = Building.new
    @information_by_floors = @building.information_by_floors.build
  end

  # 新規建物登録アクション
  def create
    @building = Building.new(building_params)
    if @building.save
      flash[:success] = "新規登録しました"
      redirect_to buildings_path
    else
      flash.now[:alert] = "登録に失敗しました"
      render :new
    end
  end

  # 建物情報編集アクション
  def edit
  end

  # 建物情報詳細アクション
  def show
    @equipments = Equipment.pluck(:item)
  end
  
  # 建物情報更新アクション
  def update
    if @building.update(building_params)
      flash[:success] = "更新しました"
      redirect_to building_path
    else
      flash.now[:alert] = "更新に失敗しました"
      render :edit
    end
  end

  # 削除するためのアクション
  def destroy
    @building.delete
    flash[:success] = "削除しました"
    redirect_to buildings_path
  end

  private
  # 共通化(建物情報取得)
  def set_up_building
    @building = Building.find(params[:id])
    @information_by_floors = @building.information_by_floors
  end

  # 共通化(formのセレクト部分)
  def set_up_form
    @entirety_useges = EntiretyUsege.order(:id)
    @floor_numbers = FloorNumber.order(:id)
    @windowlesses = Windowless.order(:id)
    @building_types = BuildingType.order(:id)
    @fire_uses = FireUse.order(:id)
    @information_by_floor_errors = [
      :"information_by_floors.floor_number_id",
      :"information_by_floors.entirety_usege_id",
      :"information_by_floors.floor_area",
      :"information_by_floors.floor_capacity",
      :"information_by_floors.windowless_id"
    ]
  end

  # アクセス制限
  def correct_user
    if current_user != @building.user
    flash[:alert] = "別のユーザーの建物情報にはアクセスできません。"
    redirect_to root_path
    end
  end

  # strong parameter
  def building_params
    params.require(:building).permit(:user_id, :id, :building_type_id, :name, :address, :entirety_usege_id, :fire_use_id, information_by_floors_attributes:[:id, :building_id, :floor_number_id , :floor_area, :floor_capacity, :windowless_id, :_destroy])
  end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
  # 消防法施行令第10条第1項
  def fire_extinguisher
    # 消防法施行令第10条第1項第1号イ
    if usege_in?(@building,[1, 3, 4, 5, 6, 12, 13, 14, 16])
      "#{@equipments[0]}が必要です（#{law(10, 1, 1, "イ")})"

    # 消防法施行令第10条第1項第1号ロ
    elsif usege_in?(@building,[7, 8]) && @building.fire_use_id == 1
      "#{@equipments[0]}が必要です（#{law(10, 1, 1, "ロ")}）"

    # 消防法施行令第10条第1項第2号イ
    elsif total_area(@building,150) && usege_in?(@building,[2, 9, 10, 11, 15, 17, 18, 19, 22, 23, 26, 27, 28, 29, 30])
      "#{@equipments[0]}が必要です（#{law(10, 1, 2, "イ")}）"

    # 消防法施行令第10条第1項第2号ロ
    elsif total_area(@building,150) && usege_in?(@building,[7, 8]) && @building.fire_use_id == 2
      "#{@equipments[0]}が必要です（#{law(10, 1, 2, "ロ")}）"

    # 消防法施行令第10条第1項第3号 
    elsif usege_in?(@building,[20, 21, 24, 25, 31]) && total_area(@building,300)
      "#{@equipments[0]}が必要です（#{law(10, 1, 3, nil)}）"

    # 消防法施行令第10条第1項第4号は少量危険物のためなし

    # 消防法施行令第10条第1項第5号
    elsif (basement_floor_number_and_area(@building, 50)) || (windowless_and_area(@building, 50)) || (more_than_3rd_floor_number_and_area(@building, 50))
      "#{@equipments[0]}が必要です（#{law(10, 1, 5, nil)}）"

    else
      "#{@equipments[0]}は必要ありません"
    end
  end

  # 消防法施行令第21条
  def automatic_fire_alarm_equipment
    # 消防法施行令第21条第1項第1号イ
    if usege_in?(@building,[6, 10, 12, 13, 14, 16, 29])
      "#{@equipments[10]}が必要です（#{law(21, 1, 1, "イ")}）"

    # 消防法施行令第21条第1項第1号ロ  
    elsif usege_in?(@building,[17])
      "#{@equipments[10]}が必要です（#{law(21, 1, 1, "ロ")}）"

    # 消防法施行令第21条第1項第2号
    elsif usege_in?(@building,[22]) && total_area(@building,200)
      "#{@equipments[10]}が必要です（#{law(21, 1, 2, nil)}）"
    
    # 消防法施行令第21条第1項第3号イ
    elsif total_area(@building,300) && usege_in?(@building,[1, 2, 3, 4, 5, 7, 8, 9, 15, 19])
      "#{@equipments[10]}が必要です（#{law(21, 1, 3, "イ")}）"

    # 消防法施行令第21条第1項第3号ロ
    elsif total_area(@building,300) && usege_in?(@building,[18])
    "#{@equipments[10]}が必要です（#{law(21, 1, 3, "ロ")}）"

    # 消防法施行令第21条第1項第4号
    elsif usege_in?(@building,[11, 20, 21, 23, 24, 26, 27, 28, 30]) && total_area(@building,500)
      "#{@equipments[10]}が必要です（#{law(21, 1, 4, nil)}）"

    # 消防法施行令第21条第1項第5は（16の3）項が関係するためなし

    # 消防法施行令第21条第1項第6号
    elsif usege_in?(@building,[25, 31]) && total_area(@building,1000)
      "#{@equipments[10]}が必要です（#{law(21, 1, 6, nil)}）"

    # 消防法施行令第21条第1項第7号は避難階段が関係するためなし

    # 消防法施行令第21条第1項第8号は指定可燃物関係のためなし

    # 消防法施行令第21条第1項第9号イ,ロは（16の2）項に関係するためなし

    # 消防法施行令第21条第1項第10号
    elsif usege_in?(@building,[3, 4, 5, 7, 8]) && ((basement_floor_number_and_area(@building, 100)) || (windowless_and_area(@building, 100)))
      "#{@equipments[10]}が必要です（#{law(21, 1, 10, nil)}）"

    # 消防法施行令第21条第1項第11号
    elsif (basement_floor_number_and_area(@building, 300)) || (windowless_and_area(@building, 300)) || (more_than_3rd_floor_number_and_area(@building, 300))
      "#{@equipments[10]}が必要です（#{law(21, 1, 11, nil)}）"
    
    # 消防法施行令第21条第1項第12号は道路のように供される部分が関係するためなし
    
    # 消防法施行令第21条第1項第13号は駐車のように供される部分が関係するためなし
    
    # 消防法施行令第21条第1項第14号
    elsif more_than_11th_floor_number(@building)
      "11階以上の部分に#{@equipments[10]}が必要です（#{law(21, 1, 14, nil)}）"
    
    # 消防法施行令第21条第1項第15号は通信機器室が関係するためなし

    else
      "#{@equipments[10]}は必要ありません"
    end 
  end

  # 消防法施行令第24条
  def emergency_alarm_equipment
    # 消防法施行令第24条第1項
    if automatic_fire_alarm_equipment == "#{@equipments[10]}が必要です"
      "非常警報器具及び設備は必要ありません"

    # 消防法施行令第24条第3項第4号
    elsif (usege_in?(@building,[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 22]) && total_capacity(@building) >= 300) || (usege_in?(@building,[11, 20, 21]) && total_capacity(@building) >= 800)
      "#{@equipments[14]}(放送設備)が必要です（#{law(24, 3, 4, nil)}）"
      
    # 消防法施行令第24条第2項第1号
    elsif automatic_fire_alarm_equipment == "#{@equipments[10]}が必要です"
      "#{@equipments[14]}は必要ありません（#{law(24, 2, 1, nil)}）"

    elsif usege_in?(@building,[10, 12, 13, 14, 15, 22]) && total_capacity(@building) >=20
      "#{@equipments[14]}が必要です（#{law(24, 2, 1, nil)}）"

    # 消防法施行令第24条第3項第3号は（16）項に関係するためなし

    # 消防法施行令第24条第2項第2号
    elsif usege_in?(@building,[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]) && ((total_capacity(@building) >= 50) || (@building.information_by_floors.where(floor_number_id: [1, 2, 3]).or(@building.information_by_floors.where('windowless_id >= ?', 2)).all.sum(:floor_capacity) >= 20))
      "#{@equipments[14]}が必要です（#{law(24, 2, 2, nil)}）"

    # 消防法施行令第24条第3項第1号は（16の2）項及び（16の3）項に関係するためなし

    # 消防法施行令第24条第3項第2号
    elsif usege_in?(@building,[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]) && ((more_than_11th_floor_number(@building)) || (@building.information_by_floors.where(floor_number_id: 1).present?))
      "#{@equipments[14]}(放送設備)が必要です（#{law(24, 3, 2, nil)}）"
      
    # 消防法施行令第24条第1項
    elsif usege_in?(@building,[9, 16, 17, 18, 19, 23, 26, 27]) && total_capacity(@building) >= 20 && total_capacity(@building) < 50
      "非常警報器具が必要です（#{law(24, 1, nil, nil)}）"

    else
      "#{@equipments[14]}及び器具は必要ありません"
    end
  end

  # 消防法施行令第25条
  def evacuation_tool
    # 消防法施行令第25条第1項第1号
    if usege_in?(@building,[12, 13, 14, 15, 16, 17, 18, 19]) && ((more_thna_2nd_floor_number_and_capacity(@building, 20)) || (basement_floor_number_and_capacity(@building, 20)))
      "#{@equipments[15]}が必要です（#{law(25, 1, 1, nil)}）"

    # 消防法施行令第25条第1項第2号
    elsif usege_in?(@building,[10, 11]) && ((more_thna_2nd_floor_number_and_capacity(@building, 30)) || (basement_floor_number_and_capacity(@building, 30)))
      "#{@equipments[15]}が必要です（#{law(25, 1, 2, nil)}）"

    # 消防法施行令第25条第1項第3号(主要構造部の仕様については考慮せず)
    elsif usege_in?(@building,[1, 2, 3, 4, 5, 6, 7, 8, 9, 20, 21, 22, 23, 24, 25]) && ((more_thna_2nd_floor_number_and_capacity(@building, 50)) || (basement_floor_number_and_capacity(@building, 50)))
      "#{@equipments[15]}が必要です（#{law(25, 1, 3, nil)}）"
    
    # 消防法施行令第25条第1項第4号
    elsif usege_in?(@building,[26, 27, 31]) && ((@building.information_by_floors.where('floor_number_id >= ?', 5).where('windowless_id >= ?', 2).where('floor_capacity >= ?', 100).present?) || (basement_floor_number_and_capacity(@building, 100)) || (more_thna_2nd_floor_number_and_capacity(@building, 150)))
      "#{@equipments[15]}が必要です（#{law(25, 1, 4, nil)}）"

    # 消防法施行令第25条第1項第5号は避難階及び避難階段が関係するためなし
    else
      "#{@equipments[15]}は必要ありません"
    end
  end

  # 消防法施行令第26条
  def guide_light
    # 消防法施行令第26条第1項第1号、消防法施行令第26条第1項第2号
    if usege_in?(@building,[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 22, 23]) 
      "#{@equipments[16]}が必要です（#{law(26, 1, 1, nil)}、#{law(26, 1, 2, nil)}）"

    elsif (usege_in?(@building,[11, 20, 21, 24, 25, 26, 27, 28, 29, 30, 31])) && (@building.information_by_floors.where('floor_number_id <= ?', 3).present?) 
      "地階部分には、#{@equipments[16]}が必要です（#{law(26, 1, 1, nil)}、#{law(26, 1, 2, nil)}）"

    elsif (usege_in?(@building,[11, 20, 21, 24, 25, 26, 27, 28, 29, 30, 31])) && (@building.information_by_floors.where('windowless_id >= ?', 2).present?) 
      "無窓階部分には、#{@equipments[16]}が必要です（#{law(26, 1, 1, nil)}、#{law(26, 1, 2, nil)}）"

    elsif (usege_in?(@building,[11, 20, 21, 24, 25, 26, 27, 28, 29, 30, 31])) && (more_than_11th_floor_number(@building))
      "11階以上の部分には、#{@equipments[16]}が必要です（#{law(26, 1, 1, nil)}、#{law(26, 1, 2, nil)}）"
    
    # 消防法施行令第26条第1項第4号
    elsif usege_in?(@building,[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])
      "誘導標識が必要です（#{law(26, 1, 4, nil)}）"

    else
      "#{@equipments[16]}は必要ありません"
    end
  end

  private

  def usege_in?(building,*n)
    building.entirety_usege_id.in?(*n)
  end

  def total_area(building,n)
    building.information_by_floors.all.sum(:floor_area) >= n
  end

  def total_capacity(building)
    building.information_by_floors.all.sum(:floor_capacity)
  end

  def basement_floor_number_and_area(building, area)
    building.information_by_floors.where('floor_number_id <= ?', 3).where('floor_area >= ?', area).present?
  end

  def more_than_3rd_floor_number_and_area(building, area)
    building.information_by_floors.where('floor_number_id >= ?', 6).where('floor_area >= ?', area).present?
  end

  def windowless_and_area(building, area)
    building.information_by_floors.where('windowless_id >= ?', 2).where('floor_area >= ?', area).present?
  end

  def more_than_11th_floor_number(building)
    building.information_by_floors.where('floor_number_id >= ?', 14).present?
  end

  def basement_floor_number_and_capacity(building, capacity)
    building.information_by_floors.where('floor_number_id <= ?', 3).where('floor_capacity >= ?', capacity).present?
  end
  def more_thna_2nd_floor_number_and_capacity(building, capacity)
    building.information_by_floors.where('floor_number_id >= ?', 5).where('floor_capacity >= ?', capacity).present?
  end

  def law(article, paragraph, item, number)
    if item.nil?
      "消防法施行令第#{article}条第#{paragraph}項"
    else
      "消防法施行令第#{article}条第#{paragraph}項第#{item}号#{number}"
    end
  end
end

app/views/buildings/_capacity.html.erb
<a class="btn-gradient-radius-mini" href="" data-toggle="modal" data-target="#capacityModal">収容人員算定表</a>
<div class="modal fade" id="capacityModal" tabindex="-1" role="dialog" aria-labelledby="capacityModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable modal-dialog-fluid" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="capacityModalTitle">収容人員</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>No.</th>
              <th>算出方法</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th>1,2</th>
              <td>
                <p>次にあげる計算方法で算出した値の合計とする。</p>
                <ul>
                  <li>従業員の数</li>
                  <li>客席の部分ごとに次の1から3までによつて算出した数の合計数</li>
                  <ol>
                    <li>固定式のいす席については、いす席の数に対応する数。※この場合において、長いす席にあっては、当いす席の正面幅を 0.4 ｍで割って得た数（1未満は切り捨て）とする。</li>
                    <li>立見席については、当部分の床面積を 0.2 ㎡で割って得た数</li>
                    <li>その他の部分については、当部分の床面積を 0.5 ㎡で割って得た数</li>
                  </ol>
                </ul>
              </td>
            </tr>
            <tr>
              <th>3, 5~8</th>
              <td>
                <p>次にあげる計算方法で算出した値の合計とする。</p>
                <ul>
                  <li>従業員の数</li>
                  <li>客席の部分ごとに次の1及び2によつて算出した数の合計数</li>
                  <ol>
                    <li>固定式のいす席については、いす席の数に対応する数。※この場合において、長いす式にあっては、当いす席の正面幅を 0.5 ｍで割って得た数（1未満は切り捨て）とする。</li>
                    <li>その他の部分については、当部分の床面積を 3 ㎡で割って得た数</li>
                  </ol>
                </ul>
              </td>
            </tr>
            <tr>
              <th>4</th>
              <td>
                <p>次にあげる計算方法で算出した値の合計とする。</p>
                <ul>
                  <li>従業員の数</li>
                  <li>遊技（囲碁、将棋、麻雀及びパチンコ屋など）のための遊具を使用して遊技を行うことができる者の数</li>
                  <li>観覧，飲食又は休憩の用に供する固定式のいす席が設けられている場合は，当いす席の数に対応する数。この場合において，長いす式のいす席にあつては，当いす席の正面幅を 0.5 ｍで割って得た数（1未満は切り捨てる）とする</li>
                </ul>
              </td>
            </tr>
            <tr>
              <th>9</th>
              <td>
                <p>次にあげる計算方法で算出した値の合計とする。</p>
                <ul>
                  <li>従業員の数</li>
                  <li>主として従業者以外の者の使用に供する部分について次の1及び2によつて算定した数の合計数</li>
                  <ol>
                    <li>飲食又は休憩の用に供する部分については，当部分の床面積を３㎡で割って得た数</li>
                    <li>その他の部分については，当部分の床面積を４㎡で割って得た数</li>
                  </ol>
                </ul>
              </td>
            </tr>
            <tr>
              <th>10</th>
              <td>
                <p>次にあげる計算方法で算出した値の合計とする。</p>
                <ul>
                  <li>従業員の数</li>
                  <li>宿泊室ごとに次の1及び2によつて算定した数の合計数</li>
                    <ol>
                      <li>洋式の宿泊室については，当宿泊室にあるベッドの数</li>
                      <li>和式の宿泊室については，当宿泊室の床面積を６㎡（簡易宿所及び主として団体客を宿泊させるものにあつては，３㎡）で割って得た数</li>
                    </ol>
                  <li>集会，飲食又は休憩の用に供する部分について次の1及び2によつて算定した数の合計数</li>
                    <ol>
                      <li>固定式のいす席を設ける部分については，当部分にあるいす席の数。この場合において，長いす式のいす席にあつては，当いす席の正面幅を 0.5 mで割って得た数（１未満は切り捨て）とする。</li>
                      <li>その他の部分については，当該部分の床面積を３㎡で割って得た数</li>
                    </ol>
                </ul>
              </td>
            </tr>
            <tr>
              <th>11</th>
              <td>居住者の数により算定する。</td>
            </tr>
            <tr>
              <th>12~15</th>
              <td>
                <p>次にあげる計算方法で算出した値の合計とする。</p>
                <ul>
                  <li>医師，歯科医師，助産師，薬剤師，看護師その他の従業者の数</li>
                  <li>病室内にある病床の数</li>
                  <li>待合室の床面積の合計を３㎡で割って得た数</li>
                </ul>
              </td>
            </tr>
            <tr>
              <th>16~18</th>
              <td>従業者の数と，老人，乳児，幼児，身体障害者，知的障害者その他の要保護者の数とを合算して算定する。</td>
            </tr>
            <tr>
              <th>19</th>
              <td>教職員の数と，幼児，児童又は生徒の数とを合算して算定する。</td>
            </tr>
            <tr>
              <th>20</th>
              <td>教職員の数と，児童，生徒又は学生の数とを合算して算定する。</td>
            </tr>
            <tr>
              <th>21</th>
              <td>従業者の数と，閲覧室，展示室，展覧室，会議室又は休憩室の床面積の合計を３㎡で割って得た数とを合算して算定する。</td>
            </tr>
            <tr>
              <th>22,23</th>
              <td>従業者の数と，浴場，脱衣場，マッサージ室及び休憩の用に供する部分の床面積の合計を３㎡で割って得た数とを合算して算定する。</td>
            </tr>
            <tr>
              <th>24,26~30</th>
              <td>従業者の数により算定する。</td>
            </tr>
            <tr>
              <th>25</th>
              <td>神職，僧侶，牧師その他従業者の数と，礼拝，集会又は休憩の用に供する部分の床面積の合計を３㎡で割って得た数とを合算して算定する。</td>
            </tr>
            <tr>
              <th>31</th>
              <td>従業者の数と，主として従業者以外の者の使用に供する部分の床面積を３㎡で割って得た数とを合算して算定する。</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/buildings/_equipment_judgement.html.erb
<a class="btn-sticky" href="" data-toggle="modal" data-target="#equipmentModal">消防用設備</a>
<div class="modal fade" id="equipmentModal" tabindex="-1" role="dialog" aria-labelledby="equipmentModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable modal-dialog-fluid " role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="equipmentModalTitle">必要な消防用設備</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table class="table table-bordered table-striped">
          <tbody>
            <tr>
              <td><%= fire_extinguisher %></td>
            </tr>
            <tr>
              <td><%= automatic_fire_alarm_equipment %></td>
            </tr>
            <tr>
              <td><%= emergency_alarm_equipment %></td>
            </tr>
            <tr>
              <td><%= evacuation_tool %></td>
            </tr>
            <tr>
              <td><%= guide_light %></td>
            </tr>
          </tbody>
        </table>
        <p>※少量危険物及び指定可燃物の貯蔵等の有無による消防用設備等の設置判定はしていません</p>
        <p>※避難階及び避難階段等の設置の有無による消防用設備等の設置判定はしていません</p>
        <% if @building.building_type_id == 2 %>
          <p>※建物内の他の部分の使用状況によって必要な消防用設備が変わる場合があります。</p>
        <% end %>
        <div class="modal-footer">
          <a class="btn-gradient-radius" data-dismiss="modal" href="">Close</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/buildings/_information_by_floor_fields.html.erb
<div class="nested-fields">
  <%= f.collection_select :floor_number_id, @floor_numbers, :id, :floor, { prompt: "階の選択" } %>
  <%= f.text_field :floor_area, autofocus: true, type: 'tel', class: 'col-sm-2 d-inline form-control', placeholder: "床面積" %>
  <%= f.text_field :floor_capacity, autofocus: true, type: 'tel', class: 'col-sm-2 d-inline form-control', placeholder: "収容人員" %>
  <%= f.collection_select :windowless_id, @windowlesses, :id, :judgement, { prompt: "無窓階判定" } %>
  <%= f.hidden_field :building_id, value: @building.id %>
  <%= link_to_remove_association("削除", f) %>
  <div class="error_message">
    <% @information_by_floor_errors.each do |i| %>
      <p><%= @building.errors.full_messages_for(i).first %></p>
    <% end %>
  </div>
</div>

app/views/buildings/index.html.erb
<div class="show_section">
  <%= link_to "登録画面へ", new_building_path, 'data-turbolinks': :false %>
  <%= will_paginate @buildings, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer%>
  <div class="container-index">
    <div class="row">
      <% @buildings.each do |building| %>
        <div class="col-sm-4 index-column">
          <img src="assets/building.png" alt="" class="img-responsive mt-3 w-100">
        </div>
        <div class="col-sm-8 index-column">
          <div class="row">
            <div class="col-sm-12">
              <h3 class="mt-4"><%= building.name %></h3>
              <p>住所：<%= building.address %></p>
              <p>用途：<%= building.entirety_usege.category %></p>
            </div>
            <div class="col-sm-4 ml-sm-auto mb-3">
              <%= link_to "詳細", building_path(building), class: "btn-sticky", 'data-turbolinks': :false %></li>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <%= will_paginate @buildings, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer%>
</div>

app/views/buildings/show.html.erb
<div class="show_section">
  <%= link_to "一覧画面へ", buildings_path, 'data-turbolinks': :false %>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="col_box clearfix">
          <div class="row">
            <div class="col-md-6">
              <h4 id="name"><%= @building.name %></h4>
              <h5 id="address">住所:<%= @building.address %></h5>
              <p>建物タイプ:<%= @building.building_type.b_type %>
              <p>用途:<%= @building.entirety_usege.category %></p>
              <p>延べ面積(㎡):<%= @building.information_by_floors.all.sum(:floor_area) %></p>
              <p>収容人員(人):<%= @building.information_by_floors.all.sum(:floor_capacity) %></p>
              <table class="table table-bordered table-striped col-lg-12">
                  <thead>
                    <tr align="center">
                      <th>階数</th>
                      <th>床面積(㎡)</th>
                      <th>収容人員(人)</th>
                      <th>無窓階判定</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @building.information_by_floors.each do |building| %>
                    <tr align="center">
                      <td><%=building.floor_number.floor %></td>
                      <td><%=building.floor_area %></td>
                      <td><%=building.floor_capacity %></td>
                      <td><%=building.windowless.judgement %></td>
                    </tr>
                    <% end %>
                  </tbody>
              </table>
              <% if [7,8].include?(@building.entirety_usege_id) %>
                <p>火気設備使用の有無:<%= @building.fire_use.fire_use_select %></p>
              <% end %>
            </div>
            <div class="col-md-6">
              <div id="gmap"></div>
              <hr>
              <div class="three-btn"> 
                <%= render partial: "equipment_judgement" %>
                <%= link_to "編集", edit_building_path(@building), class: "btn-sticky w-25 ml-4", 'data-turbolinks': :false %>
                <%= link_to "削除", building_path(@building), method: :delete, data: { confirm: "削除しますか？" }, class: "btn-sticky w-25 ml-4"%>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>